### ISSUE TITLE
Ícone com props inválidas

### ISSUE THREAD

**Issue by bernardodemarco** [pixel-ufsc/projeto-nutrijr#11]
@guicardosooliveira, em alguns ícones adicionados, os svgs estão com algumas props inválidas

![image](https://github.com/pixel-ufsc/projeto-nutrijr/assets/115510880/a382ade2-b47a-4a91-839a-9c0d4b6dfa44)

## Solução

- [ ] copiar os svgs (que estão em HTML) e jogar em alguma [ferramenta para transformar o HTML em JSX](https://transform.tools/html-to-jsx)

**Comment by guicardosooliveira** [comment]
arrumado, @bernardodemarco !
